### ISSUE TITLE
Console Logs

### ISSUE THREAD

**Issue by Taankly** [amineyarman/Kinesis.js#1]
Helo, not quite sure if i'm missing something about disabling the console logs. But right now my console is full of logs like this:
 
transformValue translate(23.104050498863568px, -8.81100882419085px)
kinesis.es.js:709 distance 644.5434204405451

Is there a way to disable logging? Or can you please remove it from the code? 

Thanks! :)

**Comment by amineyarman** [comment]
Hello!

Thank you for letting me know. I've fixed it in version 1.0.5 
You shouldn't see console.logs anymore.
