### ISSUE TITLE
Some strange wiggle at distance

### ISSUE THREAD

**Issue by Taankly** [amineyarman/Kinesis.js#2]
Hey, sadly i discovered some strange wiggle at the kinesis distance mouse event. Every time my mouse is in the center of the object its wiggling. I have some screencast so you can see what i mean. I would love to use this in my project but this wiggle is just a dealbreaker for me. Can you try to fix it? 
Thank you! :) 

If you need further informations don't hesitate do ask :)

Here is the screencast: 

https://github.com/user-attachments/assets/827c202b-81a5-4c79-9b0b-78d5e10e4202

**Comment by amineyarman** [comment]
@Taankly 
Thanks for letting me know. It's indeed a dealbreaker :D
I pushed a fix on 1.0.6, let me know if the new behavior works for you.

**Comment by Taankly** [comment]
Looks perfect for me! Thanks :)
